
-- +migrate Up
CREATE TABLE IF NOT EXISTS auth.user_profile(
    id NUMBER(20,0) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2 (100) NOT NULL,
    name NUMBER(10,0) (100) NOT NULL,
    path VARCHAR2 (100) NOT NULL,
    created_at DATE DEFAULT sysdate NOT NULL,
    updated_at DATE DEFAULT sysdate NOT NULL
);

-- +migrate Down
DROP TABLE IF EXISTS auth.user_profile;
